[tool.poetry]
name = "ex1"
version = "1.0.0"
description = "Loading programs"
authors = ["jperez-s"]

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^2.1.0"
requests = "^2.31.0"
matplotlib = "^3.7.2"
numpy = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
